cc_binary (
    name = "mphf_test",
    srcs = [
        "mphf_tests.c"
    ],
    deps = [
        "//:libcmph",
    ],
)

cc_binary (
    name = "packed_mphf_test",
    srcs = [
        "packed_mphf_tests.c"
    ],
    deps = [
        "//:libcmph",
    ],
)

cc_test (
    name = "compressed_rank",
    srcs = [
        "compressed_rank_tests.c"
    ],
    deps = [
        "//:libcmph",
    ],
)

cc_test (
    name = "compressed_seq",
    srcs = [
        "compressed_seq_tests.c"
    ],
    deps = [
        "//:libcmph",
    ],
)

cc_test (
    name = "graph",
    srcs = [
        "graph_tests.c"
    ],
    deps = [
        "//:libcmph",
    ],
)

cc_test (
    name = "select",
    srcs = [
        "select_tests.c"
    ],
    deps = [
        "//:libcmph",
    ],
)
