cc_binary (
    name = "vector_adapter_ex1",
    srcs = ["vector_adapter_ex1.c"],
    deps = [
        "//:libcmph",
    ],
)

cc_binary (
    name = "file_adapter_ex2",
    srcs = ["file_adapter_ex2.c"],
    deps = [
        "//:libcmph",
    ],
)

cc_binary (
    name = "struct_vector_adapter_ex3",
    srcs = ["struct_vector_adapter_ex3.c"],
    deps = [
        "//:libcmph",
    ],
)

cc_binary (
    name = "small_set_ex4",
    srcs = ["small_set_ex4.c"],
    deps = [
        "//:libcmph",
    ],
)
